// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMb2FEEXEh7hkZM4tZUsTG44Axl0H0QzQ',
    appId: '1:570272459044:web:13af6890d2a1856adf2bb1',
    messagingSenderId: '570272459044',
    projectId: 'spendster-75987',
    authDomain: 'spendster-75987.firebaseapp.com',
    storageBucket: 'spendster-75987.appspot.com',
    measurementId: 'G-N6BFERJCYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrwsfYx1uUxtBcU-E0TtBYT4hkXhy7XA',
    appId: '1:570272459044:android:edb8934370f623c1df2bb1',
    messagingSenderId: '570272459044',
    projectId: 'spendster-75987',
    storageBucket: 'spendster-75987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnGMCxu6ofMHy1ydAAFmTgrYE2uPC96io',
    appId: '1:570272459044:ios:67298384f47e8004df2bb1',
    messagingSenderId: '570272459044',
    projectId: 'spendster-75987',
    storageBucket: 'spendster-75987.appspot.com',
    iosBundleId: 'com.example.spendster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnGMCxu6ofMHy1ydAAFmTgrYE2uPC96io',
    appId: '1:570272459044:ios:a3d06e0bced28b66df2bb1',
    messagingSenderId: '570272459044',
    projectId: 'spendster-75987',
    storageBucket: 'spendster-75987.appspot.com',
    iosBundleId: 'com.example.spendster.RunnerTests',
  );
}
